
services:
  test: &defaults
    build:
      context: .
      target: base
    working_dir: /app
    command: go test -v ./...
    environment:
      - MYSQL_HOST=mysql_test
      - MYSQL_USER=zpe_test
      - MYSQL_PASSWORD=zpe_test
      - MYSQL_DATABASE=zpe_test
      - MYSQL_PORT=3306
      - JWT_SECRET=secret
    volumes:
      - .:/app
    depends_on:
      mysql_test:
        condition: service_healthy
  app:
    <<: *defaults
    command: go run ./main.go
    ports:
      - "8888:8888"
    env_file:
      - ./.docker/dev.env
    depends_on:
      - mysql
    environment: []
  ci:
    <<: *defaults
    build: 
      context: .
      target: ci
    volumes: []
  mysql: &mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.docker/dev.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      retries: 30
      start_period: 60s
      timeout: 5s
    ports:
      - "3306:3306"
  mysql_test:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zpe_test
      MYSQL_USER: zpe_test
      MYSQL_PASSWORD: zpe_test
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      retries: 30
      start_period: 60s
      timeout: 5s

    
