name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.59

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT
  build-and-test:
    runs-on: ubuntu-latest
    needs: detect-modules
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Run unit tests
        run: docker compose -f ./docker-compose.yaml up --abort-on-container-exit ci

      - name: Shut down services
        run: docker compose -f docker-compose.yaml down